config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :artists



  root 'artists#index'

  resources :artists do
    resources :songs
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :songs, dependent: :destroy
  has_one_attached :avatar

  validates :nickname, presence: true
  validates :nickname, uniqueness: { case_sensitive: false }
  validates :birthdate, presence: true
  validate :birthdate_in_the_future, if: :birthdate
  validates :origin, presence: true
  validates :biography, presence: true, length: { minimum: 250 }

  def birthdate_in_the_future
    errors.add(:birthdate, "can't be in the future") if birthdate > Date.today
  end
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  belongs_to :artist
  validates :title, presence: true, uniqueness: true
  validates :released, presence: true
  validate :future_release_time, if: :released
  validate :past_release_time, if: :released
  validates :duration, presence: true
end

def future_release_time
  errors.add(:released, 'is the future date') if released > Time.now
end

def past_release_time
  first_record = 1929
  released_year = released.year
  if released_year < first_record
    errors.add(:released, '- too early for records')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  def pundit_user
    current_artist
  end

  rescue_from Pundit::NotAuthorizedError, with: :artist_not_authorized

  def after_sign_in_path_for(artist)
    artist_path(artist)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[avatar nickname birthdate origin biography email_confirmation password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[avatar nickname birthdate origin biography email_confirmation password password_confirmation])
  end
end

private
def artist_not_authorized
  flash[:warning] = 'You are not authorized to perform this action.'
  redirect_to(request.referrer || root_path)
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController

  before_action :authenticate_artist!, only: [:edit, :destroy]
  PER_PAGE = 3
  def index
    @artists = Artist.order(nickname: :asc).page(params[:page]).per(PER_PAGE)
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(params[:id])
    authorize @artist
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      flash[:notice] = 'Artist has been successfully created'
      redirect_to @artist
    else
      flash[:notice] = 'Try again to create an artist'
      render 'new'
    end
  end

  def update
    @artist = Artist.find(params[:id])
    authorize @artist
    if @artist.update(artist_params)
      flash[:notice] = 'You successfully updated the artist'
      redirect_to @artist
    else
      flash[:warning] = 'Try again to update the artist'
      render 'new'
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    authorize @artist
    @artist.destroy
    flash[:notice] = 'Artist was successfully destroyed'
    redirect_to artists_path
  end
end

private
def artist_params
  params.require(:artist).permit(:avatar,:nickname, :birthdate, :origin, :biography, :email, :password, :password_confirmation)
end

app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  before_action :song_authorization, only: %i[edit update destroy]
  before_action :authenticate_artist!, except: %i[index show]
  PER_PAGE = 3
  def index
    @songs = Song.order(released: :desc).page(params[:page]).per(PER_PAGE)
  end

  def show
    @artist = Artist.find(params[:artist_id])
    @song = Song.find(params[:id])
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = Song.new
    authorize @song
  end

  def edit
    @artist = Artist.find(params[:artist_id])
    @song = Song.find(params[:id])
  end

  def create
    @song = current_artist.songs.create(song_params)
    authorize @song
    if @song.save
      flash[:success] = 'The Song has been successfully crated'
      redirect_to current_artist
    else
      flash[:danger] = 'Try again to create the song'
      render 'new'
    end
  end

  def update
    @song = current_artist.songs.find(params[:id])
    if @song.update(song_params)
      flash[:success] = 'The song was successfully updated'
      redirect_to current_artist
    else
      flash[:danger] = 'Try again to update the song'
      render 'edit'
    end
  end

  def destroy
    @song = current_artist.songs.find(params[:id])
    if @song.destroy
      flash[:success] = 'The song was sucessfully destroyed'
      redirect_to current_artist
    else
      flash[:danger] = "The song wasn't destroyed"
      render @song
    end
  end
end

private
def song_params
  params.require(:song).permit(:title, :released, :duration)
end

def song_authorization
  @song = Song.find(params[:id])
  authorize @song
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/artists/_error_messages.html.erb
<% if @artist.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@artist.errors.count, 'error') %> prohibited this artist from saving.
          </h2>
            <div class="panel-body">
              <ul>
              <% @artist.errors.full_messages.each do |msg| %>
              <li><%= msg %>.</li>
              <% end %>
              </ul>
           </div>
         </div>
       </div>
    </div>
  </div>
<% end %>

app/views/artists/_form.html.erb
<%= render 'shared/error_messages', model: @artist %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@artist, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-4">
          <%= f.label :nickname %>
        </div>
        <div class="col-sm-4">
          <%= f.text_field :nickname, class: "form-control", placeholder: "Artist's nickname", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-4">
          <%= f.label :birthdate %>
        </div>
        <div class="col-sm-4">
          <%= f.text_field :birthdate, class: "form-control", placeholder: "Dec 8 1974", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-4">
          <%= f.label :origin %>
        </div>
        <div class="col-sm-4">
          <%= f.text_field :origin %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-4">
          <%= f.label :biography %>
        </div>
        <div class="col-sm-4">
          <%= f.text_area :biography, class: "form-control", placeholder: "Bio here", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-12">
          <%= f.submit(@artist.new_record? ? "Create an Artist" : "Update an Artist", class: "btn btn-primary btn-lg") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/artists/edit.html.erb
<h1 align = "center">Edit Artist</h1>
<%= render 'form' %>

app/views/artists/index.html.erb
<h1 align = "center">All Artists</h1>
<div align="center">
  <% @artists.each do |artist| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="nickname"><%= artist.nickname %></li>
          <li><%= artist.birthdate %>, <%= artist.origin %></li>
          <%= link_to "Show the Artist", artist_path(artist), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete the Artist", artist_path(artist), method: :delete,
                                         data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </ul>
  <% end %>

  <% if current_artist %>
    <%= link_to "Edit Your account", edit_artist_registration_path(@artist), class: "btn btn-xs btn-warning" %>
    <%= link_to "Sign out #{@artist}", destroy_artist_session_path, method: :delete, data: { confirm: "Sure to log out?"},class: "btn btn-xs btn-danger"  %>
  <% else %>
    <%= link_to "Signup for Artists", new_artist_registration_path, class: "btn btn-xs btn-info"  %>
    <%= link_to "Sign in the Artist", new_artist_session_path, class: "btn btn-xs btn-warning"  %>
  <% end %>


  <%= paginate @artists %>
</div>

app/views/artists/new.html.erb
<h1 align = "center">New Artist</h1>
<%= render 'form' %>

app/views/artists/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
         <h1><%= @artist.nickname %>'s page</h1>
         <%= image_tag @artist.avatar.variant(resize: "200x200") if @artist.avatar.attached? %>
      </div>
      <div class="col-xs-6">
        <%= @artist.biography %><br>
           <% if current_artist == @artist %>
              <%= link_to "Edit yourself", edit_artist_registration_path(@artist), class: "btn btn-xs btn-primary" %>
              <%= link_to "Create a song", new_artist_song_path(@artist), class: "btn btn-xs btn-warning" %>
           <% end %>
           <%= link_to "Return to all Artists", artists_path, class: "btn btn-xs btn-success" %>

      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        Born <%= @artist.birthdate %>, <%= @artist.origin %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <% if current_artist == @artist %>
          <%= link_to "Sign out", destroy_artist_session_path, method: :delete, data: { confirm: "Sure to log out?"},class: "btn btn-xs btn-danger" %>
<% end %>
      </div>
      <div class="col-xs-6">
        <% if @artist.songs.any? %>
        <h3 align = "center"> <%= @artist.nickname %>'s songs </h3>


           <% @artist.songs.each do |song| %>
             <ul class="listing">
               <div class="row">
                  <div class="col-6">
                     Title: <h4 class="nickname"><%= song.title %></h4>
                     <li>Released: <%= song.released %>. Duration: <%= song.duration %>


                           <%= link_to "Edit the song", edit_artist_song_path(@artist, song), class: "btn btn-xs btn-primary" %>
                           <%= link_to "Delete the song", artist_song_path(@artist, song), method: :delete,
                           data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>

                    </li>
                  </div>
               </div>
             </ul>
           <% end %>
           <% end %>
         </div>
      </div>

app/views/layouts/_flash_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <%= content_tag :div, msg, id: "form_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>

app/views/layouts/_footer.html.erb
<div class="containter">
  <footer class="footer">
    <small>
      Copyright &copy; Marta Trojanowska
      <a href="https://www.google.com">GOOGLE</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", "#" %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTemplate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= debug(params) if Rails.env.development? %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(model.errors.count, 'error') %> prohibited this <%= model.class %> from saving.
          </h2>
            <div class="panel-body">
              <ul>
              <% model.errors.full_messages.each do |msg| %>
              <li><%= msg %>.</li>
              <% end %>
              </ul>
           </div>
         </div>
       </div>
    </div>
  </div>
<% end %>

app/views/songs/_song_form.html.erb
<%= render 'shared/error_messages', model: @song %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for([current_artist, @song], :html => {class: "form-horizontal", role: "form"}) do |f| %>
     <div class="form-group">
      <div class="control-label col-sm-4">
        <%= f.label :title %>
      </div>
      <div class="control-label col-sm-4">
        <%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-4">
        <%= f.label :released %>
      </div>
      <div class="control-label col-sm-4">
        <%= f.text_field :released, class: "form-control", placeholder: "Dec 08 1974", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-4">
        <%= f.label :duration %>
      </div>
      <div class="control-label col-sm-4">
        <%= f.text_field :duration, class: "form-control", placeholder: "10 min.", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-12">
        <%= f.submit(@song.new_record? ? "Create a song" : "Save the song", class: "btn btn-primary btn-lg") %>
      </div>
    </div>
      <% end %>
   </div>
 </div>

app/views/songs/edit.html.erb
<h1 align="center">Edit the song</h1>

<%= render "song_form" %>

app/views/songs/index.html.erb
<h1 align="center">List of songs</h1>
<div align="center">
  <% @songs.each do |song| %>
    <div class="row">
      <div class="col-sm-12">
        <h3 class="nickname"><%= song.title %></h3>
           Released: <%= song.released %>. Duration: <%= song.duration %>
           <%= link_to "Edit the song", edit_artist_song_path(:artist, :song), class: "btn btn-xs btn-primary" %>
      </div>
    </div>
  <% end %>
  <%= paginate @songs %>
</div>

app/views/songs/new.html.erb
<h1 align="center">New song</h1>
<%= render "song_form" %>

app/views/songs/show.html.erb
<h1 align="center"><%= @song.title %></h1>

<div align="center">
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li>Released: <%= @song.released %>.</li>
        <li>Duration: <%= @song.duration %>.</li>
      </div>
    </div
  </ul>
  <%= link_to "Edit the song", edit_artist_song_path(@artist, @song), class: "btn btn-xs btn-primary" %>
</div>